# Generated by Django 3.0.1 on 2019-12-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imageUrl', models.TextField(blank=True, null=True)),
                ('imageAlt', models.CharField(max_length=120, null=True)),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('title', models.CharField(max_length=120)),
                ('priceInCents', models.IntegerField()),
                ('formattedPrice', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('reviewCount', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
